comment: false
codecov:
  token: 88f0788d-665f-4d7c-b2a3-d4de94044db5
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true
